---
title: "work"
---

plots for 
-loudness
-key
-energy

**Motivation**
- What is the story behind the project?
- Why were you interested in the project?
- What were you motivation?
- Why is the project important?

When searching for a dataset we were intrigued by the vairbales of audio features and how they contribute to the overall popularity of a song. Music is very relavent in today's culture and our lives, and many people like a wide variety of music. We found it interesting to look at what "hidden" or subconscious elements of the song may play a role into the popular enjoyment of the track. Some of our favorite audio features that we are analyzing for popularity are danceability, valence, and energy. We are curious if these features will play a significant role within the popularity of the track. This project is important as it not only paints a picture for what current audio features tend to make a track popular, but also could help predict popularity of future songs based on their elements. 

**Background**

To understand the data we need to know what the variables represent and where they are from. The audio features and popularity scores come from the Spotify index. The Spotify Popularity Index measures what is "hot and not" in the music field. It is designed to influence what music listeners will hear. The Popularity Score is a metric that ranks overall songs and albums based on their level of listener engagement and overall appeal on platform. The score ranges from 0-100 and takes into account recent play counts, frequency, and distributions of listens. This popularity then plays a role in when and where these songs are added to Spotify playlists which then enhances the streams.

The audio features are also a measurement measured through and by Spotify. A description of each element and what they measure is listed below:

*Energy*- Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.

*Valence*- A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).

*Liveness*- Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.

*Instrumentalness*- Predicts whether a track contains no vocals. "Ooh" and "aah" sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly "vocal". The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0.

*Acousticness*- A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic.

*Speechiness*- Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.

*Danceability*- Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.


Background data gathered from:
https://help.spotontrack.com/article/what-do-the-audio-features-mean 

https://www.artist.tools/features/spotify-popularity-index#:~:text=The%20Spotify%20Popularity%20Index%20(or,and%20pitches%20to%20Editorial%20playlists 



