---
title: "A.O"
format: html
---

This article mainly discussed the skills and methods of leadership in a group, but also touched on methods of facilitating good group work and progress. These methods were primarily clear communication, recognizing the emotions (particularly frustration) that may come up during a team project, and ensuring that each member gets to contribute in some way to the product. This article also mentioned some specific examples for difficulties that may arise and the ways to address them. One of these examples was frustration that may arise due to not reaching a consensus. To reach a consensus in the first place, it is suggested to set time limits on the discussion and make sure a consensus is reached by the end of the time. They also mention that if a consensus is reached very quickly, it is good to probe each team member individually and ensure that everyone is comfortable with the decision reached. 


The link to the article can be found below:

https://hr.berkeley.edu/hr-network/central-guide-managing-hr/managing-hr/interaction/team-building/steps
